// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: zmagmacore/magmasc/pb/proto/data_marker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataMarker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataUsage *DataUsage `protobuf:"bytes,2,opt,name=data_usage,json=dataUsage,proto3" json:"data_usage"` // @gotags: json:"data_usage"
	Qos       *QoS       `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`
	PublicKey string     `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SigScheme string     `protobuf:"bytes,5,opt,name=sig_scheme,json=sigScheme,proto3" json:"sig_scheme,omitempty"`
	Signature string     `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *DataMarker) Reset() {
	*x = DataMarker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMarker) ProtoMessage() {}

func (x *DataMarker) ProtoReflect() protoreflect.Message {
	mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMarker.ProtoReflect.Descriptor instead.
func (*DataMarker) Descriptor() ([]byte, []int) {
	return file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescGZIP(), []int{0}
}

func (x *DataMarker) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataMarker) GetDataUsage() *DataUsage {
	if x != nil {
		return x.DataUsage
	}
	return nil
}

func (x *DataMarker) GetQos() *QoS {
	if x != nil {
		return x.Qos
	}
	return nil
}

func (x *DataMarker) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DataMarker) GetSigScheme() string {
	if x != nil {
		return x.SigScheme
	}
	return ""
}

func (x *DataMarker) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type DataUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DownloadBytes uint64 `protobuf:"varint,2,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	UploadBytes   uint64 `protobuf:"varint,3,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	SessionTime   uint32 `protobuf:"varint,4,opt,name=session_time,json=sessionTime,proto3" json:"session_time,omitempty"`
}

func (x *DataUsage) Reset() {
	*x = DataUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUsage) ProtoMessage() {}

func (x *DataUsage) ProtoReflect() protoreflect.Message {
	mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUsage.ProtoReflect.Descriptor instead.
func (*DataUsage) Descriptor() ([]byte, []int) {
	return file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescGZIP(), []int{1}
}

func (x *DataUsage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DataUsage) GetDownloadBytes() uint64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *DataUsage) GetUploadBytes() uint64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *DataUsage) GetSessionTime() uint32 {
	if x != nil {
		return x.SessionTime
	}
	return 0
}

type QoS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadMbps float32 `protobuf:"fixed32,1,opt,name=download_mbps,json=downloadMbps,proto3" json:"download_mbps,omitempty"`
	UploadMbps   float32 `protobuf:"fixed32,2,opt,name=upload_mbps,json=uploadMbps,proto3" json:"upload_mbps,omitempty"`
	Latency      float32 `protobuf:"fixed32,3,opt,name=latency,proto3" json:"latency,omitempty"`
}

func (x *QoS) Reset() {
	*x = QoS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QoS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoS) ProtoMessage() {}

func (x *QoS) ProtoReflect() protoreflect.Message {
	mi := &file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoS.ProtoReflect.Descriptor instead.
func (*QoS) Descriptor() ([]byte, []int) {
	return file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescGZIP(), []int{2}
}

func (x *QoS) GetDownloadMbps() float32 {
	if x != nil {
		return x.DownloadMbps
	}
	return 0
}

func (x *QoS) GetUploadMbps() float32 {
	if x != nil {
		return x.UploadMbps
	}
	return 0
}

func (x *QoS) GetLatency() float32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

var File_zmagmacore_magmasc_pb_proto_data_marker_proto protoreflect.FileDescriptor

var file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x7a, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x73, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61,
	0x73, 0x63, 0x22, 0xea, 0x01, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d,
	0x61, 0x73, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x71, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x73, 0x63, 0x2e, 0x51, 0x6f, 0x53, 0x52, 0x03,
	0x71, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x98, 0x01, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x03, 0x51, 0x6f,
	0x53, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x62,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x62, 0x70, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x6d, 0x62, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x62, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x30, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x67, 0x6f, 0x73, 0x64, 0x6b, 0x2f, 0x7a, 0x6d, 0x61,
	0x67, 0x6d, 0x61, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x73, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescOnce sync.Once
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescData = file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDesc
)

func file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescGZIP() []byte {
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescOnce.Do(func() {
		file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescData = protoimpl.X.CompressGZIP(file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescData)
	})
	return file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDescData
}

var file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zmagmacore_magmasc_pb_proto_data_marker_proto_goTypes = []interface{}{
	(*DataMarker)(nil), // 0: zchain.pb.magmasc.data_marker
	(*DataUsage)(nil),  // 1: zchain.pb.magmasc.data_usage
	(*QoS)(nil),        // 2: zchain.pb.magmasc.QoS
}
var file_zmagmacore_magmasc_pb_proto_data_marker_proto_depIdxs = []int32{
	1, // 0: zchain.pb.magmasc.data_marker.data_usage:type_name -> zchain.pb.magmasc.data_usage
	2, // 1: zchain.pb.magmasc.data_marker.qos:type_name -> zchain.pb.magmasc.QoS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zmagmacore_magmasc_pb_proto_data_marker_proto_init() }
func file_zmagmacore_magmasc_pb_proto_data_marker_proto_init() {
	if File_zmagmacore_magmasc_pb_proto_data_marker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMarker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QoS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zmagmacore_magmasc_pb_proto_data_marker_proto_goTypes,
		DependencyIndexes: file_zmagmacore_magmasc_pb_proto_data_marker_proto_depIdxs,
		MessageInfos:      file_zmagmacore_magmasc_pb_proto_data_marker_proto_msgTypes,
	}.Build()
	File_zmagmacore_magmasc_pb_proto_data_marker_proto = out.File
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_rawDesc = nil
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_goTypes = nil
	file_zmagmacore_magmasc_pb_proto_data_marker_proto_depIdxs = nil
}
