// Code generated by gobind. DO NOT EDIT.

// JNI function headers for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java wallet._base.go

#ifndef ___H__
#define ___H__

#include <jni.h>

#endif
