// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java wallet._base.go

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include ".h"


JNIEXPORT void JNICALL
Java____1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
}

