// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java command-line-arguments

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "zcncore.h"

jclass proxy_class_zcncore_AuthCallback;
jmethodID proxy_class_zcncore_AuthCallback_cons;
static jmethodID mid_AuthCallback_OnSetupComplete;
jclass proxy_class_zcncore_GetBalanceCallback;
jmethodID proxy_class_zcncore_GetBalanceCallback_cons;
static jmethodID mid_GetBalanceCallback_OnBalanceAvailable;
jclass proxy_class_zcncore_GetInfoCallback;
jmethodID proxy_class_zcncore_GetInfoCallback_cons;
static jmethodID mid_GetInfoCallback_OnInfoAvailable;
jclass proxy_class_zcncore_GetMintNonceCallback;
jmethodID proxy_class_zcncore_GetMintNonceCallback_cons;
static jmethodID mid_GetMintNonceCallback_OnBalanceAvailable;
jclass proxy_class_zcncore_GetNonceCallback;
jmethodID proxy_class_zcncore_GetNonceCallback_cons;
static jmethodID mid_GetNonceCallback_OnNonceAvailable;
jclass proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallback;
jmethodID proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallback_cons;
// skipped method GetNotProcessedZCNBurnTicketsCallback.OnBalanceAvailable with unsupported parameter or return types

jclass proxy_class_zcncore_WalletCallback;
jmethodID proxy_class_zcncore_WalletCallback_cons;
static jmethodID mid_WalletCallback_OnWalletCreateComplete;
jclass proxy_class_zcncore_BurnTicket;
jmethodID proxy_class_zcncore_BurnTicket_cons;
jclass proxy_class_zcncore_GetClientResponse;
jmethodID proxy_class_zcncore_GetClientResponse_cons;
jclass proxy_class_zcncore_GetMintNonceCallbackStub;
jmethodID proxy_class_zcncore_GetMintNonceCallbackStub_cons;
jclass proxy_class_zcncore_GetNonceCallbackStub;
jmethodID proxy_class_zcncore_GetNonceCallbackStub_cons;
jclass proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub;
jmethodID proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_cons;

JNIEXPORT void JNICALL
Java_zcncore_Zcncore__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
	clazz = (*env)->FindClass(env, "zcncore/BurnTicket");
	proxy_class_zcncore_BurnTicket = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_BurnTicket_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetClientResponse");
	proxy_class_zcncore_GetClientResponse = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetClientResponse_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetMintNonceCallbackStub");
	proxy_class_zcncore_GetMintNonceCallbackStub = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetMintNonceCallbackStub_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetNonceCallbackStub");
	proxy_class_zcncore_GetNonceCallbackStub = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetNonceCallbackStub_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetNotProcessedZCNBurnTicketsCallbackStub");
	proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyAuthCallback");
	proxy_class_zcncore_AuthCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_AuthCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/AuthCallback");
	mid_AuthCallback_OnSetupComplete = (*env)->GetMethodID(env, clazz, "onSetupComplete", "(JLjava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyGetBalanceCallback");
	proxy_class_zcncore_GetBalanceCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetBalanceCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetBalanceCallback");
	mid_GetBalanceCallback_OnBalanceAvailable = (*env)->GetMethodID(env, clazz, "onBalanceAvailable", "(JJLjava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyGetInfoCallback");
	proxy_class_zcncore_GetInfoCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetInfoCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetInfoCallback");
	mid_GetInfoCallback_OnInfoAvailable = (*env)->GetMethodID(env, clazz, "onInfoAvailable", "(JJLjava/lang/String;Ljava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyGetMintNonceCallback");
	proxy_class_zcncore_GetMintNonceCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetMintNonceCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetMintNonceCallback");
	mid_GetMintNonceCallback_OnBalanceAvailable = (*env)->GetMethodID(env, clazz, "onBalanceAvailable", "(JJLjava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyGetNonceCallback");
	proxy_class_zcncore_GetNonceCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetNonceCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetNonceCallback");
	mid_GetNonceCallback_OnNonceAvailable = (*env)->GetMethodID(env, clazz, "onNonceAvailable", "(JJLjava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyGetNotProcessedZCNBurnTicketsCallback");
	proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_GetNotProcessedZCNBurnTicketsCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/GetNotProcessedZCNBurnTicketsCallback");
	// skipped method GetNotProcessedZCNBurnTicketsCallback.OnBalanceAvailable with unsupported parameter or return types
	
	
	clazz = (*env)->FindClass(env, "zcncore/Zcncore$proxyWalletCallback");
	proxy_class_zcncore_WalletCallback = (*env)->NewGlobalRef(env, clazz);
	proxy_class_zcncore_WalletCallback_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "zcncore/WalletCallback");
	mid_WalletCallback_OnWalletCreateComplete = (*env)->GetMethodID(env, clazz, "onWalletCreateComplete", "(JLjava/lang/String;Ljava/lang/String;)V");
	
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_checkConfig(JNIEnv* env, jclass _clazz) {
	int32_t r0 = proxyzcncore__CheckConfig();
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_closeLog(JNIEnv* env, jclass _clazz) {
	proxyzcncore__CloseLog();
}

JNIEXPORT jdouble JNICALL
Java_zcncore_Zcncore_convertToToken(JNIEnv* env, jclass _clazz, jlong token) {
	int64_t _token = (int64_t)token;
	double r0 = proxyzcncore__ConvertToToken(_token);
	jdouble _r0 = (jdouble)r0;
	return _r0;
}

JNIEXPORT jdouble JNICALL
Java_zcncore_Zcncore_convertTokenToUSD(JNIEnv* env, jclass _clazz, jdouble token) {
	double _token = (double)token;
	struct proxyzcncore__ConvertTokenToUSD_return res = proxyzcncore__ConvertTokenToUSD(_token);
	jdouble _r0 = (jdouble)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jdouble JNICALL
Java_zcncore_Zcncore_convertUSDToToken(JNIEnv* env, jclass _clazz, jdouble usd) {
	double _usd = (double)usd;
	struct proxyzcncore__ConvertUSDToToken_return res = proxyzcncore__ConvertUSDToToken(_usd);
	jdouble _r0 = (jdouble)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_createWallet(JNIEnv* env, jclass _clazz, jobject statusCb) {
	int32_t _statusCb = go_seq_to_refnum(env, statusCb);
	int32_t r0 = proxyzcncore__CreateWallet(_statusCb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_createWalletOffline(JNIEnv* env, jclass _clazz) {
	struct proxyzcncore__CreateWalletOffline_return res = proxyzcncore__CreateWalletOffline();
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_cryptoJsDecrypt(JNIEnv* env, jclass _clazz, jstring passphrase, jstring encryptedMessage) {
	nstring _passphrase = go_seq_from_java_string(env, passphrase);
	nstring _encryptedMessage = go_seq_from_java_string(env, encryptedMessage);
	struct proxyzcncore__CryptoJsDecrypt_return res = proxyzcncore__CryptoJsDecrypt(_passphrase, _encryptedMessage);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_cryptoJsEncrypt(JNIEnv* env, jclass _clazz, jstring passphrase, jstring message) {
	nstring _passphrase = go_seq_from_java_string(env, passphrase);
	nstring _message = go_seq_from_java_string(env, message);
	struct proxyzcncore__CryptoJsEncrypt_return res = proxyzcncore__CryptoJsEncrypt(_passphrase, _message);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_decrypt(JNIEnv* env, jclass _clazz, jstring key, jstring text) {
	nstring _key = go_seq_from_java_string(env, key);
	nstring _text = go_seq_from_java_string(env, text);
	struct proxyzcncore__Decrypt_return res = proxyzcncore__Decrypt(_key, _text);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_encrypt(JNIEnv* env, jclass _clazz, jstring key, jstring text) {
	nstring _key = go_seq_from_java_string(env, key);
	nstring _text = go_seq_from_java_string(env, text);
	struct proxyzcncore__Encrypt_return res = proxyzcncore__Encrypt(_key, _text);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getAllocation(JNIEnv* env, jclass _clazz, jstring allocID, jobject cb) {
	nstring _allocID = go_seq_from_java_string(env, allocID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetAllocation(_allocID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getAllocations(JNIEnv* env, jclass _clazz, jstring clientID, jobject cb) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetAllocations(_clientID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getAuthorizerSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetAuthorizerSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getBalance(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetBalance(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getBalanceWallet(JNIEnv* env, jclass _clazz, jstring walletStr, jobject cb) {
	nstring _walletStr = go_seq_from_java_string(env, walletStr);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetBalanceWallet(_walletStr, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getBlobber(JNIEnv* env, jclass _clazz, jstring blobberID, jobject cb) {
	nstring _blobberID = go_seq_from_java_string(env, blobberID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetBlobber(_blobberID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getBlobberSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetBlobberSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getBlobbers(JNIEnv* env, jclass _clazz, jobject cb, jlong limit, jlong offset, jboolean active) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	nint _limit = (nint)limit;
	nint _offset = (nint)offset;
	char _active = (char)active;
	proxyzcncore__GetBlobbers(_cb, _limit, _offset, _active);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getChallengePoolInfo(JNIEnv* env, jclass _clazz, jstring allocID, jobject cb) {
	nstring _allocID = go_seq_from_java_string(env, allocID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetChallengePoolInfo(_allocID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jobject JNICALL
Java_zcncore_Zcncore_getClientDetails(JNIEnv* env, jclass _clazz, jstring clientID) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	struct proxyzcncore__GetClientDetails_return res = proxyzcncore__GetClientDetails(_clientID);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_zcncore_GetClientResponse, proxy_class_zcncore_GetClientResponse_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_getIdForUrl(JNIEnv* env, jclass _clazz, jstring url) {
	nstring _url = go_seq_from_java_string(env, url);
	nstring r0 = proxyzcncore__GetIdForUrl(_url);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

// skipped function GetLogger with unsupported parameter or return types

JNIEXPORT jlong JNICALL
Java_zcncore_Zcncore_getMinShardersVerify(JNIEnv* env, jclass _clazz) {
	nint r0 = proxyzcncore__GetMinShardersVerify();
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSCConfig(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSCConfig(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSCGlobals(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSCGlobals(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSCNodeInfo(JNIEnv* env, jclass _clazz, jstring id, jobject cb) {
	nstring _id = go_seq_from_java_string(env, id);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSCNodeInfo(_id, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSCNodePool(JNIEnv* env, jclass _clazz, jstring id, jobject cb) {
	nstring _id = go_seq_from_java_string(env, id);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSCNodePool(_id, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSCUserInfo(JNIEnv* env, jclass _clazz, jstring clientID, jobject cb) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSCUserInfo(_clientID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMinerSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMinerSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMiners(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMiners(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getMintNonce(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetMintNonce(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getNonce(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetNonce(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getNotProcessedZCNBurnTickets(JNIEnv* env, jclass _clazz, jstring ethereumAddress, jlong startNonce, jobject cb) {
	nstring _ethereumAddress = go_seq_from_java_string(env, ethereumAddress);
	int64_t _startNonce = (int64_t)startNonce;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetNotProcessedZCNBurnTickets(_ethereumAddress, _startNonce, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_getPublicEncryptionKey(JNIEnv* env, jclass _clazz, jstring mnemonic) {
	nstring _mnemonic = go_seq_from_java_string(env, mnemonic);
	struct proxyzcncore__GetPublicEncryptionKey_return res = proxyzcncore__GetPublicEncryptionKey(_mnemonic);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getReadPoolInfo(JNIEnv* env, jclass _clazz, jstring clientID, jobject cb) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetReadPoolInfo(_clientID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getSharderSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetSharderSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getSharders(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetSharders(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetSnapshots(_round, _limit, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getStakePoolInfo(JNIEnv* env, jclass _clazz, jstring blobberID, jobject cb) {
	nstring _blobberID = go_seq_from_java_string(env, blobberID);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetStakePoolInfo(_blobberID, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getStakePoolUserInfo(JNIEnv* env, jclass _clazz, jstring clientID, jlong offset, jlong limit, jobject cb) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	nint _offset = (nint)offset;
	nint _limit = (nint)limit;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetStakePoolUserInfo(_clientID, _offset, _limit, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getStorageSCConfig(JNIEnv* env, jclass _clazz, jobject cb) {
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetStorageSCConfig(_cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getTransactions(JNIEnv* env, jclass _clazz, jstring toClient, jstring fromClient, jstring block_hash, jstring sort, jlong limit, jlong offset, jobject cb) {
	nstring _toClient = go_seq_from_java_string(env, toClient);
	nstring _fromClient = go_seq_from_java_string(env, fromClient);
	nstring _block_hash = go_seq_from_java_string(env, block_hash);
	nstring _sort = go_seq_from_java_string(env, sort);
	nint _limit = (nint)limit;
	nint _offset = (nint)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetTransactions(_toClient, _fromClient, _block_hash, _sort, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getUserSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetUserSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_getValidatorSnapshots(JNIEnv* env, jclass _clazz, jlong round, jlong limit, jlong offset, jobject cb) {
	int64_t _round = (int64_t)round;
	int64_t _limit = (int64_t)limit;
	int64_t _offset = (int64_t)offset;
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__GetValidatorSnapshots(_round, _limit, _offset, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_getVersion(JNIEnv* env, jclass _clazz) {
	nstring r0 = proxyzcncore__GetVersion();
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_getWalletClientID(JNIEnv* env, jclass _clazz, jstring walletStr) {
	nstring _walletStr = go_seq_from_java_string(env, walletStr);
	struct proxyzcncore__GetWalletClientID_return res = proxyzcncore__GetWalletClientID(_walletStr);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jlong JNICALL
Java_zcncore_Zcncore_getWalletNonce(JNIEnv* env, jclass _clazz, jstring clientID) {
	nstring _clientID = go_seq_from_java_string(env, clientID);
	struct proxyzcncore__GetWalletNonce_return res = proxyzcncore__GetWalletNonce(_clientID);
	jlong _r0 = (jlong)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

// skipped function GetWalletRaw with unsupported parameter or return types

JNIEXPORT jdouble JNICALL
Java_zcncore_Zcncore_getZcnUSDInfo(JNIEnv* env, jclass _clazz) {
	struct proxyzcncore__GetZcnUSDInfo_return res = proxyzcncore__GetZcnUSDInfo();
	jdouble _r0 = (jdouble)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_init(JNIEnv* env, jclass _clazz, jstring chainConfigJSON) {
	nstring _chainConfigJSON = go_seq_from_java_string(env, chainConfigJSON);
	int32_t r0 = proxyzcncore__Init(_chainConfigJSON);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_initSignatureScheme(JNIEnv* env, jclass _clazz, jstring scheme) {
	nstring _scheme = go_seq_from_java_string(env, scheme);
	proxyzcncore__InitSignatureScheme(_scheme);
}

JNIEXPORT jboolean JNICALL
Java_zcncore_Zcncore_isMnemonicValid(JNIEnv* env, jclass _clazz, jstring mnemonic) {
	nstring _mnemonic = go_seq_from_java_string(env, mnemonic);
	char r0 = proxyzcncore__IsMnemonicValid(_mnemonic);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_zcncore_Zcncore_newBurnTicket(JNIEnv* env, jclass _clazz, jstring hash, jlong nonce) {
	nstring _hash = go_seq_from_java_string(env, hash);
	int64_t _nonce = (int64_t)nonce;
	int32_t r0 = proxyzcncore__NewBurnTicket(_hash, _nonce);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_zcncore_BurnTicket, proxy_class_zcncore_BurnTicket_cons);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_recoverOfflineWallet(JNIEnv* env, jclass _clazz, jstring mnemonic) {
	nstring _mnemonic = go_seq_from_java_string(env, mnemonic);
	struct proxyzcncore__RecoverOfflineWallet_return res = proxyzcncore__RecoverOfflineWallet(_mnemonic);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_recoverWallet(JNIEnv* env, jclass _clazz, jstring mnemonic, jobject statusCb) {
	nstring _mnemonic = go_seq_from_java_string(env, mnemonic);
	int32_t _statusCb = go_seq_to_refnum(env, statusCb);
	int32_t r0 = proxyzcncore__RecoverWallet(_mnemonic, _statusCb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_setAuthUrl(JNIEnv* env, jclass _clazz, jstring url) {
	nstring _url = go_seq_from_java_string(env, url);
	int32_t r0 = proxyzcncore__SetAuthUrl(_url);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_setLogFile(JNIEnv* env, jclass _clazz, jstring logFile, jboolean verbose) {
	nstring _logFile = go_seq_from_java_string(env, logFile);
	char _verbose = (char)verbose;
	proxyzcncore__SetLogFile(_logFile, _verbose);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_setLogLevel(JNIEnv* env, jclass _clazz, jlong lvl) {
	nint _lvl = (nint)lvl;
	proxyzcncore__SetLogLevel(_lvl);
}

// skipped function SetWallet with unsupported parameter or return types

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_setWalletInfo(JNIEnv* env, jclass _clazz, jstring jsonWallet, jboolean splitKeyWallet) {
	nstring _jsonWallet = go_seq_from_java_string(env, jsonWallet);
	char _splitKeyWallet = (char)splitKeyWallet;
	int32_t r0 = proxyzcncore__SetWalletInfo(_jsonWallet, _splitKeyWallet);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_setupAuth(JNIEnv* env, jclass _clazz, jstring authHost, jstring clientID, jstring clientKey, jstring publicKey, jstring privateKey, jstring localPublicKey, jobject cb) {
	nstring _authHost = go_seq_from_java_string(env, authHost);
	nstring _clientID = go_seq_from_java_string(env, clientID);
	nstring _clientKey = go_seq_from_java_string(env, clientKey);
	nstring _publicKey = go_seq_from_java_string(env, publicKey);
	nstring _privateKey = go_seq_from_java_string(env, privateKey);
	nstring _localPublicKey = go_seq_from_java_string(env, localPublicKey);
	int32_t _cb = go_seq_to_refnum(env, cb);
	int32_t r0 = proxyzcncore__SetupAuth(_authHost, _clientID, _clientKey, _publicKey, _privateKey, _localPublicKey, _cb);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jstring JNICALL
Java_zcncore_Zcncore_splitKeys(JNIEnv* env, jclass _clazz, jstring privateKey, jlong numSplits) {
	nstring _privateKey = go_seq_from_java_string(env, privateKey);
	nint _numSplits = (nint)numSplits;
	struct proxyzcncore__SplitKeys_return res = proxyzcncore__SplitKeys(_privateKey, _numSplits);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_zcncore_BurnTicket__1_1NewBurnTicket(JNIEnv *env, jclass clazz, jstring hash, jlong nonce) {
	nstring _hash = go_seq_from_java_string(env, hash);
	int64_t _nonce = (int64_t)nonce;
	int32_t refnum = proxyzcncore__NewBurnTicket(_hash, _nonce);
	return refnum;
}

JNIEXPORT void JNICALL
Java_zcncore_BurnTicket_setHash(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_BurnTicket_Hash_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_BurnTicket_getHash(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_BurnTicket_Hash_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_BurnTicket_setNonce(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	int64_t _v = (int64_t)v;
	proxyzcncore_BurnTicket_Nonce_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_zcncore_BurnTicket_getNonce(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	int64_t r0 = proxyzcncore_BurnTicket_Nonce_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT jint JNICALL
Java_zcncore_GetClientResponse__1_1New(JNIEnv *env, jclass clazz) {
	return new_zcncore_GetClientResponse();
}

JNIEXPORT void JNICALL
Java_zcncore_GetClientResponse_setID(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_GetClientResponse_ID_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_GetClientResponse_getID(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_GetClientResponse_ID_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_GetClientResponse_setVersion(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_GetClientResponse_Version_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_GetClientResponse_getVersion(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_GetClientResponse_Version_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_GetClientResponse_setCreationDate(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint _v = (nint)v;
	proxyzcncore_GetClientResponse_CreationDate_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_zcncore_GetClientResponse_getCreationDate(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint r0 = proxyzcncore_GetClientResponse_CreationDate_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_GetClientResponse_setPublicKey(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_GetClientResponse_PublicKey_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_GetClientResponse_getPublicKey(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_GetClientResponse_PublicKey_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_zcncore_GetMintNonceCallbackStub__1_1New(JNIEnv *env, jclass clazz) {
	return new_zcncore_GetMintNonceCallbackStub();
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_add(JNIEnv* env, jobject __this__, jlong delta) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _delta = (nint)delta;
	proxyzcncore_GetMintNonceCallbackStub_Add(o, _delta);
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_done(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxyzcncore_GetMintNonceCallbackStub_Done(o);
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_onBalanceAvailable(JNIEnv* env, jobject __this__, jlong status, jlong value, jstring info) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	int64_t _value = (int64_t)value;
	nstring _info = go_seq_from_java_string(env, info);
	proxyzcncore_GetMintNonceCallbackStub_OnBalanceAvailable(o, _status, _value, _info);
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_wait(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxyzcncore_GetMintNonceCallbackStub_Wait(o);
}

// skipped field GetMintNonceCallbackStub with unsupported type: sync.WaitGroup

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_setStatus(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint _v = (nint)v;
	proxyzcncore_GetMintNonceCallbackStub_Status_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_zcncore_GetMintNonceCallbackStub_getStatus(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint r0 = proxyzcncore_GetMintNonceCallbackStub_Status_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_setValue(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	int64_t _v = (int64_t)v;
	proxyzcncore_GetMintNonceCallbackStub_Value_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_zcncore_GetMintNonceCallbackStub_getValue(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	int64_t r0 = proxyzcncore_GetMintNonceCallbackStub_Value_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_GetMintNonceCallbackStub_setInfo(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_GetMintNonceCallbackStub_Info_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_GetMintNonceCallbackStub_getInfo(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_GetMintNonceCallbackStub_Info_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_zcncore_GetNonceCallbackStub__1_1New(JNIEnv *env, jclass clazz) {
	return new_zcncore_GetNonceCallbackStub();
}

JNIEXPORT void JNICALL
Java_zcncore_GetNonceCallbackStub_onNonceAvailable(JNIEnv* env, jobject __this__, jlong status, jlong nonce, jstring info) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	int64_t _nonce = (int64_t)nonce;
	nstring _info = go_seq_from_java_string(env, info);
	proxyzcncore_GetNonceCallbackStub_OnNonceAvailable(o, _status, _nonce, _info);
}

JNIEXPORT jint JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub__1_1New(JNIEnv *env, jclass clazz) {
	return new_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub();
}

JNIEXPORT void JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_add(JNIEnv* env, jobject __this__, jlong delta) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _delta = (nint)delta;
	proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Add(o, _delta);
}

JNIEXPORT void JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_done(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Done(o);
}

// skipped function GetNotProcessedZCNBurnTicketsCallbackStub.OnBalanceAvailable with unsupported parameter or return types

JNIEXPORT void JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_wait(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Wait(o);
}

// skipped field GetNotProcessedZCNBurnTicketsCallbackStub with unsupported type: sync.WaitGroup

JNIEXPORT void JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_setStatus(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint _v = (nint)v;
	proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Status_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_getStatus(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint r0 = proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Status_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

// skipped field GetNotProcessedZCNBurnTicketsCallbackStub with unsupported type: []*command-line-arguments.BurnTicket

JNIEXPORT void JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_setInfo(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Info_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_zcncore_GetNotProcessedZCNBurnTicketsCallbackStub_getInfo(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyzcncore_GetNotProcessedZCNBurnTicketsCallbackStub_Info_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyAuthCallback_onSetupComplete(JNIEnv* env, jobject __this__, jlong status, jstring err) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	nstring _err = go_seq_from_java_string(env, err);
	proxyzcncore_AuthCallback_OnSetupComplete(o, _status, _err);
}

void cproxyzcncore_AuthCallback_OnSetupComplete(int32_t refnum, nint status, nstring err) {
	JNIEnv *env = go_seq_push_local_frame(2);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_AuthCallback, proxy_class_zcncore_AuthCallback_cons);
	jlong _status = (jlong)status;
	jstring _err = go_seq_to_java_string(env, err);
	(*env)->CallVoidMethod(env, o, mid_AuthCallback_OnSetupComplete, _status, _err);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyGetBalanceCallback_onBalanceAvailable(JNIEnv* env, jobject __this__, jlong status, jlong value, jstring info) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	int64_t _value = (int64_t)value;
	nstring _info = go_seq_from_java_string(env, info);
	proxyzcncore_GetBalanceCallback_OnBalanceAvailable(o, _status, _value, _info);
}

void cproxyzcncore_GetBalanceCallback_OnBalanceAvailable(int32_t refnum, nint status, int64_t value, nstring info) {
	JNIEnv *env = go_seq_push_local_frame(3);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_GetBalanceCallback, proxy_class_zcncore_GetBalanceCallback_cons);
	jlong _status = (jlong)status;
	jlong _value = (jlong)value;
	jstring _info = go_seq_to_java_string(env, info);
	(*env)->CallVoidMethod(env, o, mid_GetBalanceCallback_OnBalanceAvailable, _status, _value, _info);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyGetInfoCallback_onInfoAvailable(JNIEnv* env, jobject __this__, jlong op, jlong status, jstring info, jstring err) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _op = (nint)op;
	nint _status = (nint)status;
	nstring _info = go_seq_from_java_string(env, info);
	nstring _err = go_seq_from_java_string(env, err);
	proxyzcncore_GetInfoCallback_OnInfoAvailable(o, _op, _status, _info, _err);
}

void cproxyzcncore_GetInfoCallback_OnInfoAvailable(int32_t refnum, nint op, nint status, nstring info, nstring err) {
	JNIEnv *env = go_seq_push_local_frame(4);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_GetInfoCallback, proxy_class_zcncore_GetInfoCallback_cons);
	jlong _op = (jlong)op;
	jlong _status = (jlong)status;
	jstring _info = go_seq_to_java_string(env, info);
	jstring _err = go_seq_to_java_string(env, err);
	(*env)->CallVoidMethod(env, o, mid_GetInfoCallback_OnInfoAvailable, _op, _status, _info, _err);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyGetMintNonceCallback_onBalanceAvailable(JNIEnv* env, jobject __this__, jlong status, jlong value, jstring info) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	int64_t _value = (int64_t)value;
	nstring _info = go_seq_from_java_string(env, info);
	proxyzcncore_GetMintNonceCallback_OnBalanceAvailable(o, _status, _value, _info);
}

void cproxyzcncore_GetMintNonceCallback_OnBalanceAvailable(int32_t refnum, nint status, int64_t value, nstring info) {
	JNIEnv *env = go_seq_push_local_frame(3);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_GetMintNonceCallback, proxy_class_zcncore_GetMintNonceCallback_cons);
	jlong _status = (jlong)status;
	jlong _value = (jlong)value;
	jstring _info = go_seq_to_java_string(env, info);
	(*env)->CallVoidMethod(env, o, mid_GetMintNonceCallback_OnBalanceAvailable, _status, _value, _info);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyGetNonceCallback_onNonceAvailable(JNIEnv* env, jobject __this__, jlong status, jlong nonce, jstring info) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	int64_t _nonce = (int64_t)nonce;
	nstring _info = go_seq_from_java_string(env, info);
	proxyzcncore_GetNonceCallback_OnNonceAvailable(o, _status, _nonce, _info);
}

void cproxyzcncore_GetNonceCallback_OnNonceAvailable(int32_t refnum, nint status, int64_t nonce, nstring info) {
	JNIEnv *env = go_seq_push_local_frame(3);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_GetNonceCallback, proxy_class_zcncore_GetNonceCallback_cons);
	jlong _status = (jlong)status;
	jlong _nonce = (jlong)nonce;
	jstring _info = go_seq_to_java_string(env, info);
	(*env)->CallVoidMethod(env, o, mid_GetNonceCallback_OnNonceAvailable, _status, _nonce, _info);
	go_seq_pop_local_frame(env);
}

// skipped function GetNotProcessedZCNBurnTicketsCallback.OnBalanceAvailable with unsupported parameter or return types

// skipped method GetNotProcessedZCNBurnTicketsCallback with unsupported parameter or return types

JNIEXPORT void JNICALL
Java_zcncore_Zcncore_00024proxyWalletCallback_onWalletCreateComplete(JNIEnv* env, jobject __this__, jlong status, jstring wallet, jstring err) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nint _status = (nint)status;
	nstring _wallet = go_seq_from_java_string(env, wallet);
	nstring _err = go_seq_from_java_string(env, err);
	proxyzcncore_WalletCallback_OnWalletCreateComplete(o, _status, _wallet, _err);
}

void cproxyzcncore_WalletCallback_OnWalletCreateComplete(int32_t refnum, nint status, nstring wallet, nstring err) {
	JNIEnv *env = go_seq_push_local_frame(3);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_zcncore_WalletCallback, proxy_class_zcncore_WalletCallback_cons);
	jlong _status = (jlong)status;
	jstring _wallet = go_seq_to_java_string(env, wallet);
	jstring _err = go_seq_to_java_string(env, err);
	(*env)->CallVoidMethod(env, o, mid_WalletCallback_OnWalletCreateComplete, _status, _wallet, _err);
	go_seq_pop_local_frame(env);
}

