// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.AuthCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * AuthCallback needs to be implemented by the caller SetupAuth()
 */
public interface AuthCallback {
	/**
	 * This call back gives the status of the Two factor authenticator(zauth) setup.
	 */
	public void onSetupComplete(long status, String err);
	
}

