// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetMintNonceCallbackStub is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * Implementation of GetMintNonceCallback
 */
public final class GetMintNonceCallbackStub implements Seq.Proxy, GetBalanceCallback, GetMintNonceCallback {
	static { Zcncore.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	GetMintNonceCallbackStub(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public GetMintNonceCallbackStub() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field GetMintNonceCallbackStub.WaitGroup with unsupported type: sync.WaitGroup
	
	public final native long getStatus();
	public final native void setStatus(long v);
	
	public final native long getValue();
	public final native void setValue(long v);
	
	public final native String getInfo();
	public final native void setInfo(String v);
	
	public native void add(long delta);
	public native void done();
	public native void onBalanceAvailable(long status, long value, String info);
	public native void wait();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof GetMintNonceCallbackStub)) {
		    return false;
		}
		GetMintNonceCallbackStub that = (GetMintNonceCallbackStub)o;
		// skipped field GetMintNonceCallbackStub.WaitGroup with unsupported type: sync.WaitGroup
		
		long thisStatus = getStatus();
		long thatStatus = that.getStatus();
		if (thisStatus != thatStatus) {
		    return false;
		}
		long thisValue = getValue();
		long thatValue = that.getValue();
		if (thisValue != thatValue) {
		    return false;
		}
		String thisInfo = getInfo();
		String thatInfo = that.getInfo();
		if (thisInfo == null) {
			if (thatInfo != null) {
			    return false;
			}
		} else if (!thisInfo.equals(thatInfo)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getStatus(), getValue(), getInfo()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("GetMintNonceCallbackStub").append("{");
		b.append("Status:").append(getStatus()).append(",");
		b.append("Value:").append(getValue()).append(",");
		b.append("Info:").append(getInfo()).append(",");
		return b.append("}").toString();
	}
}

