// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetMintNonceCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * GetMintNonceCallback needs to be implemented by the caller of GetMintNonce() to get the status
 */
public interface GetMintNonceCallback {
	public void onBalanceAvailable(long status, long value, String info);
	
}

