// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetNotProcessedZCNBurnTicketsCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * GetNotProcessedZCNBurnTicketsCallback needs to be implemented by the caller of GetNotProcessedZCNBurnTickets() to get the status
 */
public interface GetNotProcessedZCNBurnTicketsCallback {
	public void onBalanceAvailable(long status, BurnTickets value, String info);
	
}

