// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetNonceCallbackStub is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

public final class GetNonceCallbackStub implements Seq.Proxy, GetNonceCallback {
	static { Zcncore.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	GetNonceCallbackStub(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public GetNonceCallbackStub() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void onNonceAvailable(long status, long nonce, String info);
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof GetNonceCallbackStub)) {
		    return false;
		}
		GetNonceCallbackStub that = (GetNonceCallbackStub)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("GetNonceCallbackStub").append("{");
		return b.append("}").toString();
	}
}

