// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.WalletCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * WalletCallback needs to be implemented for wallet creation.
 */
public interface WalletCallback {
	public void onWalletCreateComplete(long status, String wallet, String err);
	
}

