ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

GOMODCORE           := $(GOMODBASE)/zcncore
VERSION_FILE        := $(ROOT_DIR)/core/version/version.go
MAJOR_VERSION       := "1.0"

PLATFORM:=$(shell uname -s | tr "[:upper:]" "[:lower:]")

include _util/printer.mk
include _util/build_$(PLATFORM).mk
include _util/herumi.mk
include _util/build_mobile.mk

.PHONY: build-tools install-all herumi-all gosdk-all sdkver help

default: help

#GO BUILD SDK
gomod-download:
	go mod download -json

gomod-clean:
	go clean -i -r -x -modcache  ./...

clean-gosdk:

gosdk-build: gomod-download
	go build -x -v -tags bn256 ./...

sdkver:
	cd _sdkver; go build -o sdkver sdkver.go; ./sdkver

gosdk-test:
	go test -tags bn256 ./...

install-gosdk: | gosdk-build gosdk-test

getrev:
	$(eval VERSION_STR=$(shell git describe --tags --dirty --always))
	@echo "" > $(VERSION_FILE)
	@echo "//====== THIS IS AUTOGENERATED FILE. DO NOT MODIFY ========" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)
	@echo "package version" >> $(VERSION_FILE)
	@echo const VERSIONSTR = \"$(VERSION_STR)\" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)

install: install-herumi install-gosdk sdkver

clean: clean-gosdk clean-herumi
	@rm -rf $(OUTDIR)

help:
	@echo "Environment: "
	@echo "\tPLATFORM.......:$(PLATFORM)"
	@echo "\tGOPATH.........:$(GOPATH)"
	@echo "\tGOROOT.........:$(GOROOT)"
	@echo "\tBLS branch.....:$(bls_branch)"
	@echo "\tMCL branch.....:$(mcl_branch)"
	@echo ""
	@echo "Supported commands:"
	@echo "\tmake help              - Display environment and make targets"
	@echo "\tmake build-tools       - Install go, jq and supporting tools required for build"
	@echo "\tmake install           - Install herumi and gosdk"
	@echo "\tmake install-herumi    - Install herumi library"
	@echo "\tmake install-gosdk     - Install gosdk. Prerequiste is install-herumi"
	@echo "\tmake clean             - Deletes all build output files"
