ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

GOMODCORE           := $(GOMODBASE)/zcncore
VERSION_FILE        := $(ROOT_DIR)/core/version/version.go
MAJOR_VERSION       := "1.0"

PLATFORMOS := $(shell uname | tr "[:upper:]" "[:lower:]")

include _util/printer.mk
include _util/herumi.mk

.PHONY: install-all herumi-all gosdk-all show

default: help show

#GO BUILD SDK
gomod-download:
	go mod download -json

gomod-clean:
	go clean --modcache

gosdk-clean:
	go clean -i -r -x -modcache  ./...

gosdk-build: gomod-download
	go build -x -v -tags bn256 ./...

gosdk-test:
	go test -tags bn256 ./...

gosdk-all: | gosdk-build gosdk-test

getrev:
	$(eval VERSION_STR=$(MAJOR_VERSION).$(shell git rev-list --count HEAD))
	$(eval VERSION_STR=$(VERSION_STR)-$(shell git describe --tags --dirty --always))
	@echo "" > $(VERSION_FILE)
	@echo "//====== THIS IS AUTOGENERATED FILE. DO NOT MODIFY ========" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)
	@echo "package version" >> $(VERSION_FILE)
	@echo const VERSIONSTR = \"$(VERSION_STR)\" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)

install-all: herumi-all gosdk-all

clean:
	@rm -rf $(OUTDIR)

show:
	@echo "GOPATH=$(GOPATH)"
	@echo "GOROOT=$(GOROOT)"
	@echo "BLS git branch=$(bls_branch)"
	@echo "MCL git branch=$(mcl_branch)"

help:
	@echo "Supported commands:"
	@ecgo "\tmake show              - Display environment and make variables"
	@echo "\tmake install-all       - Install all build and project dependencies"
	@echo "\tmake gosdk-all         - Install GO modules and packages"
	@echo "\tmake herumi-all        - Download, build and install HERUMI packages"
	@echo "\tmake clean             - Deletes all the built output files"
