// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	fileref "github.com/0chain/gosdk/zboxcore/fileref"
	mock "github.com/stretchr/testify/mock"
)

// AllocationChange is an autogenerated mock type for the AllocationChange type
type AllocationChange struct {
	mock.Mock
}

// GetAffectedPath provides a mock function with given fields:
func (_m *AllocationChange) GetAffectedPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSize provides a mock function with given fields:
func (_m *AllocationChange) GetSize() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// ProcessChange provides a mock function with given fields: rootRef
func (_m *AllocationChange) ProcessChange(rootRef *fileref.Ref) error {
	ret := _m.Called(rootRef)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fileref.Ref) error); ok {
		r0 = rf(rootRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
