// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/0chain/gosdk/zboxcore/sdk"
	mock "github.com/stretchr/testify/mock"
)

// ChunkedUploadProgressStorer is an autogenerated mock type for the ChunkedUploadProgressStorer type
type ChunkedUploadProgressStorer struct {
	mock.Mock
}

// Load provides a mock function with given fields: id
func (_m *ChunkedUploadProgressStorer) Load(id string) *sdk.UploadProgress {
	ret := _m.Called(id)

	var r0 *sdk.UploadProgress
	if rf, ok := ret.Get(0).(func(string) *sdk.UploadProgress); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.UploadProgress)
		}
	}

	return r0
}

// Remove provides a mock function with given fields: id
func (_m *ChunkedUploadProgressStorer) Remove(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: up
func (_m *ChunkedUploadProgressStorer) Save(up sdk.UploadProgress) {
	_m.Called(up)
}

type mockConstructorTestingTNewChunkedUploadProgressStorer interface {
	mock.TestingT
	Cleanup(func())
}

// NewChunkedUploadProgressStorer creates a new instance of ChunkedUploadProgressStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChunkedUploadProgressStorer(t mockConstructorTestingTNewChunkedUploadProgressStorer) *ChunkedUploadProgressStorer {
	mock := &ChunkedUploadProgressStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
