// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/0chain/gosdk/zboxcore/sdk"
	mock "github.com/stretchr/testify/mock"
)

// ChunkedUploadOption is an autogenerated mock type for the ChunkedUploadOption type
type ChunkedUploadOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: su
func (_m *ChunkedUploadOption) Execute(su *sdk.ChunkedUpload) {
	_m.Called(su)
}

type mockConstructorTestingTNewChunkedUploadOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewChunkedUploadOption creates a new instance of ChunkedUploadOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChunkedUploadOption(t mockConstructorTestingTNewChunkedUploadOption) *ChunkedUploadOption {
	mock := &ChunkedUploadOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
