// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/0chain/gosdk/zboxcore/sdk"
	mock "github.com/stretchr/testify/mock"
)

// DownloadOption is an autogenerated mock type for the DownloadOption type
type DownloadOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: do
func (_m *DownloadOption) Execute(do *sdk.DownloadOptions) {
	_m.Called(do)
}

type mockConstructorTestingTNewDownloadOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewDownloadOption creates a new instance of DownloadOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDownloadOption(t mockConstructorTestingTNewDownloadOption) *DownloadOption {
	mock := &DownloadOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
