// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	fasthttp "github.com/hitenjain14/fasthttp"

	time "time"
)

// FastClient is an autogenerated mock type for the FastClient type
type FastClient struct {
	mock.Mock
}

// DoTimeout provides a mock function with given fields: req, resp, timeout
func (_m *FastClient) DoTimeout(req *fasthttp.Request, resp *fasthttp.Response, timeout time.Duration) error {
	ret := _m.Called(req, resp, timeout)

	if len(ret) == 0 {
		panic("no return value specified for DoTimeout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fasthttp.Request, *fasthttp.Response, time.Duration) error); ok {
		r0 = rf(req, resp, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFastClient creates a new instance of FastClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFastClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *FastClient {
	mock := &FastClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
