// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/0chain/gosdk/zboxcore/sdk"
	mock "github.com/stretchr/testify/mock"
)

// LiveUploadOption is an autogenerated mock type for the LiveUploadOption type
type LiveUploadOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: lu
func (_m *LiveUploadOption) Execute(lu *sdk.LiveUpload) {
	_m.Called(lu)
}

type mockConstructorTestingTNewLiveUploadOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewLiveUploadOption creates a new instance of LiveUploadOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLiveUploadOption(t mockConstructorTestingTNewLiveUploadOption) *LiveUploadOption {
	mock := &LiveUploadOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
