// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	fileref "github.com/0chain/gosdk/zboxcore/fileref"
	mock "github.com/stretchr/testify/mock"
)

// RefEntity is an autogenerated mock type for the RefEntity type
type RefEntity struct {
	mock.Mock
}

// CalculateHash provides a mock function with given fields:
func (_m *RefEntity) CalculateHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAttributes provides a mock function with given fields:
func (_m *RefEntity) GetAttributes() fileref.Attributes {
	ret := _m.Called()

	var r0 fileref.Attributes
	if rf, ok := ret.Get(0).(func() fileref.Attributes); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(fileref.Attributes)
	}

	return r0
}

// GetCreatedAt provides a mock function with given fields:
func (_m *RefEntity) GetCreatedAt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHash provides a mock function with given fields:
func (_m *RefEntity) GetHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLookupHash provides a mock function with given fields:
func (_m *RefEntity) GetLookupHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *RefEntity) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetNumBlocks provides a mock function with given fields:
func (_m *RefEntity) GetNumBlocks() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetPath provides a mock function with given fields:
func (_m *RefEntity) GetPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPathHash provides a mock function with given fields:
func (_m *RefEntity) GetPathHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSize provides a mock function with given fields:
func (_m *RefEntity) GetSize() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetType provides a mock function with given fields:
func (_m *RefEntity) GetType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUpdatedAt provides a mock function with given fields:
func (_m *RefEntity) GetUpdatedAt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
