// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SignFunc is an autogenerated mock type for the SignFunc type
type SignFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: hash
func (_m *SignFunc) Execute(hash string) (string, error) {
	ret := _m.Called(hash)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSignFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewSignFunc creates a new instance of SignFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSignFunc(t mockConstructorTestingTNewSignFunc) *SignFunc {
	mock := &SignFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
