// // Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	"github.com/stretchr/testify/mock"
)

// TransactionCallback is an autogenerated mock type for the TransactionCallback type
type TransactionCallbackImpl struct {
	mock.Mock
}

// OnAuthComplete provides a mock function with given fields: t, status
// func (_m TransactionCallbackImpl) OnAuthComplete(t Transaction, status int) {
// 	_m.Called(t, status)
// }

// // OnTransactionComplete provides a mock function with given fields: t, status
// func (_m TransactionCallbackImpl) OnTransactionComplete(t *zcncore.Transaction, status int) {
// 	_m.Called(t, status)
// }

// // OnVerifyComplete provides a mock function with given fields: t, status
// func (_m TransactionCallbackImpl) OnVerifyComplete(t *zcncore.Transaction, status int) {
// 	_m.Called(t, status)
// }

func (_m TransactionCallbackImpl) OnWalletCreateComplete(status int, wallet string, err string) {
	_m.Called(status, wallet, err)
}
