package sdk

import "github.com/0chain/gosdk/core/sys"

const DefaultBlocksPerMarker int = 100

// DownloadOption set download option
type DownloadOption func(do *DownloadOptions)

// WithVerifyDownload set verify download option for the download request options.
// If true, the response will contain proof of the download to be verified at the client side.
// 		- shouldVerify: true to verify download, false to not verify download.
func WithVerifyDownload(shouldVerify bool) DownloadOption {
	return func(do *DownloadOptions) {
		do.verifyDownload = shouldVerify
	}
}

// WithAllocation set allocation object of the download option
func WithAllocation(obj *Allocation) DownloadOption {
	return func(do *DownloadOptions) {
		do.allocationObj = obj
	}
}

// WithBlocks set block range for the download request options.
// 		- start: start block number
// 		- end: end block number
// 		- blocksPerMarker: number of blocks to download
func WithBlocks(start, end int64, blocksPerMarker int) DownloadOption {
	return func(do *DownloadOptions) {
		if start > 0 && end > 0 && end >= start {
			do.isBlockDownload = true

			do.startBlock = start
			do.endBlock = end
		}

		do.blocksPerMarker = blocksPerMarker
		if do.blocksPerMarker < 1 {
			do.blocksPerMarker = DefaultBlocksPerMarker
		}

		SetNumBlockDownloads(do.blocksPerMarker)
	}
}

// WithOnlyThumbnail set thumbnail download option which makes the request download only the thumbnail.
// 		- thumbnail: true to download only thumbnail, false to download the file.
func WithOnlyThumbnail(thumbnail bool) DownloadOption {
	return func(do *DownloadOptions) {
		do.isThumbnailDownload = thumbnail
	}
}

// WithAuthTicket set auth ticket and lookup hash for the download request options
// This is used to download shared files.
// 		- authTicket: is the ticket that is generated by the owner of the file to access their shared file.
// 		- lookupHash: is an augmented hash of the allocation ID and the path of the file, used to locate the file.
func WithAuthticket(authTicket, lookupHash string) DownloadOption {
	return func(do *DownloadOptions) {
		if len(authTicket) > 0 {
			do.isViewer = true
			do.authTicket = authTicket
			do.lookupHash = lookupHash
		}
	}
}

// WithFileHandler set file handler for the download request options
func WithFileHandler(fileHandler sys.File) DownloadOption {
	return func(do *DownloadOptions) {
		do.fileHandler = fileHandler
		do.isFileHandlerDownload = true
	}
}
