package sdk

import (
	"encoding/base64"
	"encoding/json"
	"fmt"

	"github.com/0chain/errors"
	"github.com/0chain/gosdk_common/core/screstapi"
	"github.com/0chain/gosdk_common/core/transaction"

	"github.com/0chain/gosdk_common/core/client"
	"github.com/0chain/gosdk_common/core/version"
	"github.com/0chain/gosdk_common/zboxcore/commonsdk"
	"github.com/0chain/gosdk_common/zboxcore/marker"
)

const STORAGE_SCADDRESS = "6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7"
const MINERSC_SCADDRESS = "6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d9"
const ZCNSC_SCADDRESS = "6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712e0"

var sdkNotInitialized = errors.New("sdk_not_initialized", "SDK is not initialised")
var allocationNotFound = errors.New("couldnt_find_allocation", "Couldn't find the allocation required for update")

const (
	OpUpload            int = 0
	OpDownload          int = 1
	OpRepair            int = 2
	OpUpdate            int = 3
	opThumbnailDownload int = 4
)

type StatusCallback interface {
	Started(allocationId, filePath string, op int, totalBytes int)
	InProgress(allocationId, filePath string, op int, completedBytes int, data []byte)
	Error(allocationID string, filePath string, op int, err error)
	Completed(allocationId, filePath string, filename string, mimetype string, size int, op int)
	RepairCompleted(filesRepaired int)
}

var (
	numBlockDownloads         = 100
	networkWorkerTimerInHours = 1 //nolint:unused
	singleClientMode          = false
	shouldVerifyHash          = true
)

func SetSingleClietnMode(mode bool) {
	singleClientMode = mode
}

func SetShouldVerifyHash(verify bool) {
	shouldVerifyHash = verify
}

// GetVersion - returns version string
func GetVersion() string {
	return version.VERSIONSTR
}

// GetAllocationFromAuthTicket - get allocation from given auth ticket hash.
// AuthTicket is used to access free allocations, and it's generated by the Free Storage Assigner.
//   - authTicket: the auth ticket hash
//
// returns the allocation instance and error if any
func GetAllocationFromAuthTicket(authTicket string) (*Allocation, error) {
	if !client.IsSDKInitialized() {
		return nil, sdkNotInitialized
	}
	sEnc, err := base64.StdEncoding.DecodeString(authTicket)
	if err != nil {
		return nil, errors.New("auth_ticket_decode_error", "Error decoding the auth ticket."+err.Error())
	}
	at := &marker.AuthTicket{}
	err = json.Unmarshal(sEnc, at)
	if err != nil {
		return nil, errors.New("auth_ticket_decode_error", "Error unmarshaling the auth ticket."+err.Error())
	}
	return GetAllocation(at.AllocationID)
}

// GetAllocation - get allocation from given allocation id
//
//   - allocationID: the allocation id
//
// returns the allocation instance and error if any
func GetAllocation(allocationID string) (*Allocation, error) {
	if !client.IsSDKInitialized() {
		return nil, sdkNotInitialized
	}
	params := make(map[string]string)
	params["allocation"] = allocationID
	allocationBytes, err := screstapi.MakeSCRestAPICall(STORAGE_SCADDRESS, "/allocation", params)
	if err != nil {
		return nil, errors.New("allocation_fetch_error", "Error fetching the allocation."+err.Error())
	}

	allocationObj := &Allocation{}
	err = json.Unmarshal(allocationBytes, allocationObj)
	if err != nil {
		return nil, errors.New("allocation_decode_error", "Error decoding the allocation: "+err.Error()+" "+string(allocationBytes))
	}
	allocationObj.numBlockDownloads = numBlockDownloads
	allocationObj.InitAllocation()
	return allocationObj, nil
}

// GetAllocationForUpdate - get allocation for update from given allocation id without calling init allocation
func GetAllocationForUpdate(allocationID string) (*Allocation, error) {
	if !client.IsSDKInitialized() {
		return nil, sdkNotInitialized
	}
	params := make(map[string]string)
	params["allocation"] = allocationID
	allocationBytes, err := screstapi.MakeSCRestAPICall(STORAGE_SCADDRESS, "/allocation", params)
	if err != nil {
		return nil, errors.New("allocation_fetch_error", "Error fetching the allocation."+err.Error())
	}

	allocationObj := &Allocation{}
	err = json.Unmarshal(allocationBytes, allocationObj)
	if err != nil {
		return nil, errors.New("allocation_decode_error", "Error decoding the allocation: "+err.Error()+" "+string(allocationBytes))
	}
	return allocationObj, nil
}

func GetAllocationUpdates(allocation *Allocation) error {
	if allocation == nil {
		return errors.New("allocation_not_initialized", "")
	}

	params := make(map[string]string)
	params["allocation"] = allocation.ID
	allocationBytes, err := screstapi.MakeSCRestAPICall(STORAGE_SCADDRESS, "/allocation", params)
	if err != nil {
		return errors.New("allocation_fetch_error", "Error fetching the allocation."+err.Error())
	}

	updatedAllocationObj := new(Allocation)
	if err := json.Unmarshal(allocationBytes, updatedAllocationObj); err != nil {
		return errors.New("allocation_decode_error", "Error decoding the allocation."+err.Error())
	}

	allocation.DataShards = updatedAllocationObj.DataShards
	allocation.ParityShards = updatedAllocationObj.ParityShards
	allocation.Size = updatedAllocationObj.Size
	allocation.Expiration = updatedAllocationObj.Expiration
	allocation.Payer = updatedAllocationObj.Payer
	allocation.Blobbers = updatedAllocationObj.Blobbers
	allocation.Stats = updatedAllocationObj.Stats
	allocation.TimeUnit = updatedAllocationObj.TimeUnit
	allocation.BlobberDetails = updatedAllocationObj.BlobberDetails
	allocation.ReadPriceRange = updatedAllocationObj.ReadPriceRange
	allocation.WritePriceRange = updatedAllocationObj.WritePriceRange
	allocation.ChallengeCompletionTime = updatedAllocationObj.ChallengeCompletionTime
	allocation.StartTime = updatedAllocationObj.StartTime
	allocation.Finalized = updatedAllocationObj.Finalized
	allocation.Canceled = updatedAllocationObj.Canceled
	allocation.MovedToChallenge = updatedAllocationObj.MovedToChallenge
	allocation.MovedBack = updatedAllocationObj.MovedBack
	allocation.MovedToValidators = updatedAllocationObj.MovedToValidators
	allocation.FileOptions = updatedAllocationObj.FileOptions
	allocation.IsEnterprise = updatedAllocationObj.IsEnterprise
	return nil
}

// SetNumBlockDownloads - set the number of block downloads, needs to be between 1 and 500 (inclusive). Default is 20.
//   - num: the number of block downloads
func SetNumBlockDownloads(num int) {
	if num > 0 && num <= 500 {
		numBlockDownloads = num
	}
}

// GetAllocations - get all allocations for the current client
//
// returns the list of allocations and error if any
func GetAllocations() ([]*Allocation, error) {
	return GetAllocationsForClient(client.Id())
}

func getAllocationsInternal(clientID string, limit, offset int) ([]*Allocation, error) {
	params := make(map[string]string)
	params["client"] = clientID
	params["limit"] = fmt.Sprint(limit)
	params["offset"] = fmt.Sprint(offset)
	allocationsBytes, err := screstapi.MakeSCRestAPICall(STORAGE_SCADDRESS, "/allocations", params)
	if err != nil {
		return nil, errors.New("allocations_fetch_error", "Error fetching the allocations."+err.Error())
	}

	allocations := make([]*Allocation, 0)
	err = json.Unmarshal(allocationsBytes, &allocations)
	if err != nil {
		return nil, errors.New("allocations_decode_error", "Error decoding the allocations."+err.Error())
	}
	return allocations, nil
}

// GetAllocationsForClient - get all allocations for given client id
//
//   - clientID: the client id
//
// returns the list of allocations and error if any
func GetAllocationsForClient(clientID string) ([]*Allocation, error) {
	if !client.IsSDKInitialized() {
		return nil, sdkNotInitialized
	}
	limit, offset := 20, 0

	allocations, err := getAllocationsInternal(clientID, limit, offset)
	if err != nil {
		return nil, err
	}

	var allocationsFin []*Allocation
	allocationsFin = append(allocationsFin, allocations...)
	for {
		// if the len of output returned is less than the limit it means this is the last round of pagination
		if len(allocations) < limit {
			break
		}

		// get the next set of blobbers
		offset += 20
		allocations, err = getAllocationsInternal(clientID, limit, offset)
		if err != nil {
			return allocations, err
		}
		allocationsFin = append(allocationsFin, allocations...)

	}
	return allocationsFin, nil
}

// TransferAllocation transfers the ownership of an allocation to a new owner. (txn: `storagesc.update_allocation_request`)
//
//   - allocationId is the id of the allocation.
//   - newOwner is the client id of the new owner.
//   - newOwnerPublicKey is the public key of the new owner.
//
// returns the hash of the transaction, the nonce of the transaction and an error if any.
func TransferAllocation(allocationId, newOwner, newOwnerPublicKey string) (string, int64, error) {
	if !client.IsSDKInitialized() {
		return "", 0, sdkNotInitialized
	}

	alloc, err := GetAllocation(allocationId)
	if err != nil {
		return "", 0, allocationNotFound
	}

	var allocationRequest = map[string]interface{}{
		"id":                         allocationId,
		"owner_id":                   newOwner,
		"owner_public_key":           newOwnerPublicKey,
		"size":                       0,
		"expiration_date":            0,
		"update_terms":               false,
		"add_blobber_id":             "",
		"remove_blobber_id":          "",
		"set_third_party_extendable": alloc.ThirdPartyExtendable,
		"file_options_changed":       false,
		"file_options":               alloc.FileOptions,
	}
	var sn = transaction.SmartContractTxnData{
		Name:      transaction.STORAGESC_UPDATE_ALLOCATION,
		InputArgs: allocationRequest,
	}
	hash, _, n, _, err := commonsdk.StorageSmartContractTxn(sn)
	return hash, n, err
}
