// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	zcncore "github.com/0chain/gosdk/zcncore"
	mock "github.com/stretchr/testify/mock"
)

// FeeOption is an autogenerated mock type for the FeeOption type
type FeeOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *FeeOption) Execute(_a0 *zcncore.TxnFeeOption) {
	_m.Called(_a0)
}

// NewFeeOption creates a new instance of FeeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeeOption {
	mock := &FeeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
