// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetBalanceCallback is an autogenerated mock type for the GetBalanceCallback type
type GetBalanceCallback struct {
	mock.Mock
}

// OnBalanceAvailable provides a mock function with given fields: status, value, info
func (_m *GetBalanceCallback) OnBalanceAvailable(status int, value int64, info string) {
	_m.Called(status, value, info)
}

// NewGetBalanceCallback creates a new instance of GetBalanceCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBalanceCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBalanceCallback {
	mock := &GetBalanceCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
