// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetInfoCallback is an autogenerated mock type for the GetInfoCallback type
type GetInfoCallback struct {
	mock.Mock
}

// OnInfoAvailable provides a mock function with given fields: op, status, info, err
func (_m *GetInfoCallback) OnInfoAvailable(op int, status int, info string, err string) {
	_m.Called(op, status, info, err)
}
