// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetMintNonceCallback is an autogenerated mock type for the GetMintNonceCallback type
type GetMintNonceCallback struct {
	mock.Mock
}

// OnBalanceAvailable provides a mock function with given fields: status, value, info
func (_m *GetMintNonceCallback) OnBalanceAvailable(status int, value int64, info string) {
	_m.Called(status, value, info)
}

type mockConstructorTestingTNewGetMintNonceCallback interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetMintNonceCallback creates a new instance of GetMintNonceCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetMintNonceCallback(t mockConstructorTestingTNewGetMintNonceCallback) *GetMintNonceCallback {
	mock := &GetMintNonceCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
