// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetNonceCallback is an autogenerated mock type for the GetNonceCallback type
type GetNonceCallback struct {
	mock.Mock
}

// OnNonceAvailable provides a mock function with given fields: status, nonce, info
func (_m *GetNonceCallback) OnNonceAvailable(status int, nonce int64, info string) {
	_m.Called(status, nonce, info)
}

// NewGetNonceCallback creates a new instance of GetNonceCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetNonceCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetNonceCallback {
	mock := &GetNonceCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
