// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	zcncore "github.com/0chain/gosdk/zcncore"
	mock "github.com/stretchr/testify/mock"
)

// GetNotProcessedZCNBurnTicketsCallback is an autogenerated mock type for the GetNotProcessedZCNBurnTicketsCallback type
type GetNotProcessedZCNBurnTicketsCallback struct {
	mock.Mock
}

// OnBalanceAvailable provides a mock function with given fields: status, value, info
func (_m *GetNotProcessedZCNBurnTicketsCallback) OnBalanceAvailable(status int, value []zcncore.BurnTicket, info string) {
	_m.Called(status, value, info)
}

type mockConstructorTestingTNewGetNotProcessedZCNBurnTicketsCallback interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetNotProcessedZCNBurnTicketsCallback creates a new instance of GetNotProcessedZCNBurnTicketsCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetNotProcessedZCNBurnTicketsCallback(t mockConstructorTestingTNewGetNotProcessedZCNBurnTicketsCallback) *GetNotProcessedZCNBurnTicketsCallback {
	mock := &GetNotProcessedZCNBurnTicketsCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
