// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetUSDInfoCallback is an autogenerated mock type for the GetUSDInfoCallback type
type GetUSDInfoCallback struct {
	mock.Mock
}

// OnUSDInfoAvailable provides a mock function with given fields: status, info, err
func (_m *GetUSDInfoCallback) OnUSDInfoAvailable(status int, info string, err string) {
	_m.Called(status, info, err)
}
