// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MSVoteCallback is an autogenerated mock type for the MSVoteCallback type
type MSVoteCallback struct {
	mock.Mock
}

// OnVoteComplete provides a mock function with given fields: status, proposal, err
func (_m *MSVoteCallback) OnVoteComplete(status int, proposal string, err string) {
	_m.Called(status, proposal, err)
}
