// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MSVoteCallback is an autogenerated mock type for the MSVoteCallback type
type MSVoteCallback struct {
	mock.Mock
}

// OnVoteComplete provides a mock function with given fields: status, proposal, err
func (_m *MSVoteCallback) OnVoteComplete(status int, proposal string, err string) {
	_m.Called(status, proposal, err)
}

type mockConstructorTestingTNewMSVoteCallback interface {
	mock.TestingT
	Cleanup(func())
}

// NewMSVoteCallback creates a new instance of MSVoteCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMSVoteCallback(t mockConstructorTestingTNewMSVoteCallback) *MSVoteCallback {
	mock := &MSVoteCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
