// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	zcncore "github.com/0chain/gosdk/zcncore"
	mock "github.com/stretchr/testify/mock"
)

// TransactionCallback is an autogenerated mock type for the TransactionCallback type
type TransactionCallback struct {
	mock.Mock
}

// OnAuthComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnAuthComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}

// OnTransactionComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnTransactionComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}

// OnVerifyComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnVerifyComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}
