// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	zcncore "github.com/0chain/gosdk/zcncore"
	mock "github.com/stretchr/testify/mock"
)

// TransactionCallback is an autogenerated mock type for the TransactionCallback type
type TransactionCallback struct {
	mock.Mock
}

// OnAuthComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnAuthComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}

// OnTransactionComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnTransactionComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}

// OnVerifyComplete provides a mock function with given fields: t, status
func (_m *TransactionCallback) OnVerifyComplete(t *zcncore.Transaction, status int) {
	_m.Called(t, status)
}

// NewTransactionCallback creates a new instance of TransactionCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionCallback {
	mock := &TransactionCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
