// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WalletCallback is an autogenerated mock type for the WalletCallback type
type WalletCallback struct {
	mock.Mock
}

// OnWalletCreateComplete provides a mock function with given fields: status, wallet, err
func (_m *WalletCallback) OnWalletCreateComplete(status int, wallet string, err string) {
	_m.Called(status, wallet, err)
}
