package main

import "net/http"

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

// curl google.com

func main() {
	resp, err := http.Get("https://www.google.com")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
}
