// Code generated by gobind. DO NOT EDIT.

// Java class . is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java wallet._base.go
package ;

import go.Seq;

public abstract class  {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private () {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
}
