@startuml
participant "<size:20><&terminal></size> ./zbox get-diff" as cli
collections gosdk

cli -> gosdk: GetAllocationDiff(localcache, localpath, filter, exclPath)

gosdk -> gosdk: validate localSycnCachePath
gosdk -> gosdk: build a map for exclude path
gosdk -> gosdk: get flat file list from remote
gosdk -> gosdk: get flat file list on the local filesystem
gosdk -> gosdk: get the file diff with operation
gosdk --> cli: return file diff
@enduml
