@startuml
participant "<size:20><&terminal></size> ./zbox get" as cli
collections gosdk

cli -> gosdk: GetAllocation(allocationID)

gosdk -> gosdk: check initialized sdk
gosdk -> gosdk: make SC rest api call
gosdk -> gosdk: create new allocation
gosdk -> gosdk: return response result for allocation
gosdk -> gosdk: init allocation
gosdk --> cli: return allocation
@enduml
