@startuml
participant "<size:20><&terminal></size> ./zbox rp-lock" as cli
collections gosdk

cli -> gosdk: ReadPoolLock()
gosdk -> gosdk: check initialized sdk
gosdk -> gosdk: create lock request
gosdk -> gosdk: create smart contract txn data
gosdk -> gosdk: send smart contract txn value fee
@enduml
