@startuml
participant "<size:20><&terminal></size> ./zbox rp-unlock" as cli
collections gosdk

cli -> gosdk: ReadPoolUnlock()
gosdk -> gosdk: check initialized sdk
gosdk -> gosdk: create unlock request
gosdk -> gosdk: create smart contract txn data
gosdk -> gosdk: send smart contract txn value fee
@enduml
