@startuml
participant "<size:20><&terminal></size> ./zbox sign-data" as cli
collections gosdk

cli -> gosdk: ReadPoolUnlock()
cli -> gosdk: Sign(data)
gosdk -> gosdk: create signature
group for each client key (key, idx)
gosdk -> gosdk: create new signature scheme
gosdk -> gosdk: set private key
alt length of signature equal 0
gosdk -> gosdk: sign hash to signature 
else
gosdk -> gosdk: add hash to signature
end
end

gosdk --> cli: return signature
@enduml
