@startuml
participant "<size:20><&terminal></size> ./zbox update-attributes" as cli
collections gosdk
collections blobber

cli -> gosdk: GetAllocation(allocID)
cli -> gosdk: GetFileMeta(remotePath)
cli -> gosdk: UpdateObjectAttributes(remotePath, attrs)

gosdk -> gosdk: check initialized allocation
gosdk -> gosdk: check valid path
gosdk -> gosdk: create attributes request

group for each blobber (blobber, bidx)
gosdk -> blobber: call http request to get object tree
gosdk -> blobber: call http request to update attribute
alt successful status code
gosdk -> gosdk: increase consensus and change attributesMask
end
end

gosdk -> gosdk: check threshold consensus
gosdk -> gosdk: create commit request

group for each bit 1 in the attributesMask
gosdk -> blobber: add commit request
end

group for each successful commit
gosdk -> gosdk: increase consensus
end

gosdk -> gosdk: check threshold consensus
@enduml
