// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetBalanceCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * GetBalanceCallback needs to be implemented by the caller of GetBalance() to get the status
 */
public interface GetBalanceCallback {
	public void onBalanceAvailable(long status, long value, String info);
	
}

