// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetInfoCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * GetInfoCallback needs to be implemented by the caller of GetLockTokenConfig() and GetLockedTokens()
 */
public interface GetInfoCallback {
	/**
	 * OnInfoAvailable will be called when GetLockTokenConfig is complete
	if status == StatusSuccess then info is valid
	is status != StatusSuccess then err will give the reason
	 */
	public void onInfoAvailable(long op, long status, String info, String err);
	
}

