// Code generated by gobind. DO NOT EDIT.

// Java class zcncore.GetNonceCallback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java command-line-arguments
package zcncore;

import go.Seq;

/**
 * GetNonceCallback needs to be implemented by the caller of GetNonce() to get the status
 */
public interface GetNonceCallback {
	public void onNonceAvailable(long status, long nonce, String info);
	
}

