block_worker: https://demo.0chain.net/dns
signature_scheme: bls0chain
min_submit: 50 # in percentage
min_confirmation: 50 # in percentage
confirmation_chain_length: 3  
ethereum_node_url: https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4