name: CI


on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Unit Test
        run: make gosdk-test
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: 0chain/blobber
          path: blobber
          ref: grpc_v2
      - name: Build test environment and run tests
        run: |
          git clone https://github.com/0chain/blobber.git
          cd blobber
          sed -i '/#expose_ci_port/c\    ports:\n      - "5432:5432"' ./docker.local/b0docker-compose.yml
          ./docker.local/bin/blobber.init.setup.sh
          docker network create --driver=bridge --subnet=198.18.0.0/15 --gateway=198.18.0.255 testnet0
          ./docker.local/bin/build.blobber.sh
          cd docker.local/blobber1
          ../bin/blobber.start_bls.sh </dev/null &>/dev/null &
          cd ../..
          cd ..
          make gosdk-integration-test
