name: CI

on:
  [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - uses: actions/checkout@v2
    - name: Install golangci-lint
      run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
        golangci-lint --version
    - name: Lint
      run: make lint
