name: TRIGGER_0DNS

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of 0dns to build'
        required: true
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

jobs:
  zdns:
    name: Triggering 0dns Build
    runs-on: [self-hosted, build]
    
    steps:
    - name: Generating JSON for Input
      id: get_tag
      run: |
          JSON=$(echo {\"latest_tag\":\"$TAG\"})
          echo ::set-output name=JSON::${JSON}
      env:
        TAG: ${{ github.event.inputs.latest_tag }}

    - name: Triggering 0dns Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: 0dns
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build-&-publish-docker-image.yml
        ref: ${{ github.event.inputs.branch_ref }} 
        inputs: ${{ steps.get_tag.outputs.JSON }}
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

    - name: Completing Trigger
      run: |
        echo "Tag ${TAG}."
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
      env:
        TAG: ${{ github.event.inputs.latest_tag }}
