name: WebAssembly-0nft

concurrency:
  group: "wasm-0nft-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches:
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:
    inputs:
      wasm_sdk_0nft:
        description: '0Chain WebAssembly SDK version'
        required: true

env:
  RELEASE: false
  PR: false
  
jobs:
  build:
    name: wasm-0nft-release
    runs-on: [self-hosted, build]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set GITHUB_ENV
        id: set_github_env
        run: |
          TAG=$(echo ${GITHUB_REF#refs/tags/})
          if [[ -n "${{github.event.inputs.wasm_sdk_0nft}}" ]]; then
            # create PR
            echo "PR=true" >> $GITHUB_ENV
            wasm_sdk_0nft="{\"wasm_sdk_0nft\":\"${{github.event.inputs.wasm_sdk_0nft}}\"}"
            echo "wasm_sdk_0nft=${wasm_sdk_0nft}" >> $GITHUB_ENV
          elif [[ ${TAG} = v*\.*\.* ]] ; then
            # create PR
            echo "PR=true" >> $GITHUB_ENV
            wasm_sdk_0nft="{\"wasm_sdk_0nft\":\"${TAG}\"}"
            echo "wasm_sdk_0nft=${wasm_sdk_0nft}" >> $GITHUB_ENV
            # upload zcn.wasm on release
            echo "RELEASE=true" >> $GITHUB_ENV
            echo "TAG=${TAG}" >> $GITHUB_ENV
          fi
             
      - name: Build
        run: CGO_ENABLED=0 GOOS=js GOARCH=wasm go build -o ./zcn.wasm  ./wasmsdk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if:  env.RELEASE == 'true'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zcn.wasm
          tag: ${{ env.TAG }}
          overwrite: true
          file_glob: true

      - name: Create PR on 0nft
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        if:  env.PR == 'true'
        with:
          owner: 0chain
          repo: 0nft
          ref: staging
          github_token: ${{ secrets.GOSDK }}
          workflow_file_name: webassembly-0nft.yml
          inputs: ${{ env.wasm_sdk_0nft }}
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: zcn.wasm
          path: zcn.wasm
          retention-days: 30
