name: Webassembly

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches:
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:
    inputs:
      wasm_sdk:
        description: 'webassembly sdk version'
        required: true

env:
  RELEASE: false
  PR: false
  
jobs:
  build:
    name: Build & Release
    runs-on: [self-hosted, build]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set GITHUB_ENV
        id: set_github_env
        run: |
          TAG=$(echo ${GITHUB_REF#refs/tags/})
          if [[ -n "${{github.event.inputs.wasm_sdk}}" ]]; then
            # create PR
            echo "PR=true" >> $GITHUB_ENV

            WASM_SDK="{\"wasm_sdk\":\"${{github.event.inputs.wasm_sdk}}\"}"
            echo "WASM_SDK=${WASM_SDK}" >> $GITHUB_ENV

          elif [[ ${TAG} = v*\.*\.* ]] ; then
            # create PR
            echo "PR=true" >> $GITHUB_ENV

            WASM_SDK="'{\"wasm_sdk\":\"${{github.event.inputs.wasm_sdk}}\"}'"
            echo "WASM_SDK=${WASM_SDK}" >> $GITHUB_ENV

            # upload zcn.wasm on release
            echo "RELEASE=true" >> $GITHUB_ENV
            echo "TAG=${TAG}" >> $GITHUB_ENV
          fi
             
      - name: Build
        run: CGO_ENABLED=0 GOOS=js GOARCH=wasm go build -o ./zcn.wasm  ./wasmsdk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if:  env.RELEASE == 'true'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zcn.wasm
          tag: ${{ env.TAG }}
          overwrite: true
          file_glob: true

      - name: Create PR on block-explorer
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        if:  env.PR == 'true'
        with:
          owner: 0chain
          repo: block-explorer
          ref: staging
          github_token: ${{ secrets.GOSDK }}
          workflow_file_name: webassembly.yml
          inputs: ${{ env.WASM_SDK }}
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        if:  env.RELEASE == 'true'
        with:
          name: zcn.wasm
          path: zcn.wasm
          retention-days: 30